### ISSUE TITLE
NPM deprecation bug

### ISSUE THREAD

**Issue by aalykiot** [nodeshift/npcheck#31]
The way the correct depreciation check is happening is through this:

```js
const isDeprecated = pkg.deprecated === 'this version has been deprecated';
```

But in some cases, the pkg.deprecated might be `pkg.deprecated: "replaced by <some-npm-package>"` (if the package author wants to add an additional message) and NPcheck currently misses that.

Depreciation check needs improvment!

**Comment by richardlau** [comment]
`pkg.deprecated` might be anything the package author decides to put there. Anything other than the empty string `""` (no spaces), which npm interprets to mean undeprecate (in which case I don't know if the `deprecated` field is included as an empty string or omitted altogether).

https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

**Comment by aalykiot** [comment]
I guess the check should be:

1. Is there a deprecation field present?
2. If yes, is the field an empty string?

Output: NOT DEPRECATED

Otherwise it's deprecated with message ...
