### ISSUE TITLE
Using tags when no releases found?

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/npcheck#36]
`No releases found for the passport module`

Maybe it is possible to use tags instead of releases for the cases where the project has no "official releases" in GitHub?

```
curl --silent "https://api.github.com/repos/jaredhanson/passport/tags" 
[
  {
    "name": "v0.4.1",
...
```

It returns the correct value probably after this check https://github.com/nodeshift/npcheck/blob/main/src/plugins/maintenance.js#L24
should send a request to the `tags` instead of `releases` to get the data.

I really mean another  `await fetchGithub(` inside that `if` but pointing to tags.

**Comment by aalykiot** [comment]
@helio-frota when the #35 PR is merged we will no longer fetch release info from GitHub. (https://github.com/nodeshift/npcheck/pull/35/files)

**Comment by helio-frota** [comment]
@aalykiot awesome then!
closing
