### ISSUE TITLE
Enhance support check

### ISSUE THREAD

**Issue by mhdawson** [nodeshift/npcheck#57]
Based on discussion in the latest Ref Arch meeting:

For modules that we currently report that we cannot figure out if the current LTS versions are supported the following additional checks would be good:

1) Does the module include Native code (may use Nan or Node-api but does not have to)
2) If it the modules is native and we cannot tell if it supports LTS versions, further warn that modules is native and does not use Node-API.

**Comment by aalykiot** [comment]
@mhdawson how do we know that an NPM package uses Native code ?? Does it specify a field in the package.json ?? Maybe a specific file we can look for on its repo ?? 🤔

**Comment by mhdawson** [comment]
This has some checks: https://github.com/juliangruber/is-native-module/blob/master/index.js  but is out of date as we'd definitely want to check for node-addon-api as well.

I think the safest check is to look to see if the package contains any C source files (.c, .cxx, etc.)

We can then tell if it uses Node-api if it depends on node-addon-api or references node_api.h directly.

**Comment by aalykiot** [comment]
So, if a package uses the Node-API  (node-addon-api) we can then be confident that supports the LTS versions ?? (this is the only thing still fuzzy to me)

**Comment by helio-frota** [comment]
closing since this commit already solves this issue:
https://github.com/nodeshift/npcheck/commit/b08360c0b725e8dc2af0468ed841550ce8240ce1

```
This commit adds a check and an additional warning message for modules
where the LTS version cannot be determined. If the module is a native
module (NAN, or a C++ addon) the warnings message should contain a
message saying that the module is a native module and that it does not
use N-API.
```
